Move fetching of services to controller to avoid n+1 queries
Retrospring/retrospring pull request #1014
Opened 2023-01-28 20:43 UTC by raccube

2023-01-28 21:20 UTC, pixeldesu requested changes

2023-01-28 21:20 UTC, pixeldesu commented on app/views/inbox/_entry.html.haml
> +      - if @services.count.positive?
Please pass the `@services` into the entry partial so you can use it as `services` and avoid the haml-lint warning.

2023-01-28 21:23 UTC, nilsding commented on app/controllers/inbox_controller.rb
> -      redirect_to inbox_path(last_id: params[:last_id])
hmm, I just realised that I wanted to return early in that case ...

2023-01-28 21:56 UTC, nilsding commented on app/views/inbox/show.html.haml
> +    = render "inbox/entry", services: , i:
dog says:
```suggestion
    = render "inbox/entry", services:, i:
```

2023-01-28 21:56 UTC, nilsding approved these changes

2023-01-29 22:07 UTC, pixeldesu approved these changes

2023-01-29 22:07 UTC, merged