Add new raised text and raised accent text theme fields
Retrospring/retrospring pull request #1017
Opened 2023-01-29 20:03 UTC by pixeldesu

Partially resolves #944.

This adds more options to modify text on raised content, whereas the text on the white/gray sections can now be set independently.

**Before testing:**
* Please create a theme and set `Body text` to a non-default value.

**When testing:**
* Don't forget to run `yarn run build` and `yarn run build:css`

**Testing:**
* Set the `Raised text` and `Raised accent text` theme values and check if the preview works and if everything with the styling is okay.

2023-01-29 20:04 UTC, nilsding commented on db/migrate/20230129194809_use_body_text_for_raised_texts_in_themes.rb
> +    execute <<~SQUIRREL
Oachkatzl haaßt des!

2023-01-29 21:03 UTC, raccube approved these changes
Tested locally.

2023-01-30 15:46 UTC, nilsding requested changes
the code works fine and does what it should.

I'm not too sure about the new role of _Body text colour_ though -- it's now literally just the text that's not inside anything that's raised.  It probably would be better to move things around in the theme settings page to make changing the colours of the raised content more prominent.

2023-01-31 07:58 UTC, pixeldesu commented
@nilsding I moved the "Raised Content" section to the second position now, between "General" and "Colours"

2023-01-31 07:59 UTC, nilsding approved these changes

2023-01-31 11:57 UTC, merged