Pre-load own mute relationships in follow lists
Retrospring/retrospring pull request #1037
Opened 2023-02-01 22:22 UTC by raccube

Turns out we were still getting 𝑛+1s here as mutes got missed.

2023-02-01 22:31 UTC, pixeldesu requested changes

2023-02-01 22:31 UTC, pixeldesu commented on app/controllers/user_controller.rb
> +      type:           :friend,
```suggestion
      type:           :follower,
```

2023-02-01 23:07 UTC, pixeldesu approved these changes

2023-02-02 04:47 UTC, nilsding approved these changes

2023-02-02 11:07 UTC, merged