Highlight direct questions in own question lists
Retrospring/retrospring pull request #1056
Opened 2023-02-06 14:36 UTC by raccube

Resolves #1038

2023-02-06 14:56 UTC, pixeldesu requested changes
Please localize the strings

2023-02-10 19:10 UTC, nilsding approved these changes

2023-02-11 02:16 UTC, pixeldesu requested changes
Not sure if I like this UI-wise.

If a lot of questions are direct this adds a lot of additional height to the list (and repeated text). I'd prefer it if (similar to anonymous questions) the icon is present in the header, and the explanation is added as an alert at the top of the question list.

2023-02-12 02:29 UTC, pixeldesu approved these changes

2023-02-12 17:21 UTC, merged