Added TurboStreamable concern
Retrospring/retrospring pull request #1064
Opened 2023-02-11 05:37 UTC by pixeldesu

_Toasts in `turbo_stream` responses? For errors even?_

For a long time I kinda struggled with the best ways to implement this and I kinda found a way to achieve this now.

I added a `TurboStreamable` concern which adds toast capability for success/error messages.

Handling of errors is "somewhat" automated. The concern uses the `turbo_stream_actions` method of the parent controller to figure out which actions use Turbo Stream responses, and these actions get wrapped with an error handler that renders a toast for the most common exception types (analogous to `AjaxController`)

It also adds the general `render_toast` method to the invoking controller, adding the ability to send success toast messages. I implemented this into `Settings::MutesController` and `AnonymousBlocksController` (while I was at it, I also fixed #997)

**Testing:**
* Test toasts for anonymous block/mute rule creation and deletion
* Test error toasts
  * _Hint: The easiest way to achieve this one is to create a mute rule and then adjust the action path in the delete button to point to a different ID_

2023-02-11 07:28 UTC, nilsding requested changes
please add some tests too

2023-02-11 07:28 UTC, nilsding commented on app/controllers/concerns/turbo_streamable.rb
> +  end
this does not do what you want it to: `controller` is the class itself, which will never respond to the instance method `turbo_stream_actions` (unless you define it as `self.turbo_stream_actions), so the error action will never be applied.

there's a much nicer way to achieve what you want, e.g.:

```suggestion
  class_methods do
    def turbo_stream_actions(*actions)
      around_action :handle_error, only: actions
    end
  end

  def render_toast(message, success = true)
    turbo_stream.append("toasts", partial: "shared/toast", locals: { message:, success: })
  end
```

with that you can include the module right at the beginning of the class, and then just call `turbo_stream_actions :create, :destroy` wherever you need it.

2023-02-11 07:28 UTC, nilsding commented on app/controllers/anonymous_block_controller.rb
> +  include TurboStreamable
```suggestion
  include TurboStreamable

  before_action :authenticate_user!

  turbo_stream_actions :create, :destroy
```

2023-02-11 07:28 UTC, nilsding commented on app/controllers/settings/mutes_controller.rb
> +  include TurboStreamable
```suggestion
  include TurboStreamable

  before_action :authenticate_user!

  turbo_stream_actions :create, :destroy
```

2023-02-12 01:29 UTC, pixeldesu commented
Okay, so I increased the test coverage.

Rubocop and haml-lint actions seem to fail because something is broken about the Setup Ruby action? Doesn't break just in this PR.

2023-02-12 07:58 UTC, nilsding approved these changes

2023-02-12 07:58 UTC, nilsding commented on spec/controllers/concerns/turbo_streamable_spec.rb
> +describe ApplicationController, type: :controller do
```suggestion
describe TurboStreamable, type: :controller do
```

2023-02-12 18:10 UTC, raccube approved these changes

2023-02-12 19:16 UTC, merged