Update devise to 4.9.0
Retrospring/retrospring pull request #1093
Opened 2023-02-18 16:59 UTC by raccube

2023-03-16 07:03 UTC, nilsding requested changes
tested:

- sign up
- resend confirmation instructions
- sign in without 2FA (signs in, but doesn't redirect to the timeline)
- sign in with 2FA (works fine)
- sign out
- password changing from the user settings 
- password recovery (changes the password, but doesn't redirect to the timeline)

2023-03-23 07:59 UTC, nilsding commented on app/controllers/user/sessions_controller.rb
> +     render "auth/two_factor_authentication"
```suggestion
    render "auth/two_factor_authentication"
```

2023-03-23 08:01 UTC, nilsding approved these changes

2023-03-23 08:02 UTC, nilsding commented
works fine now!

2023-03-26 12:57 UTC, pixeldesu approved these changes

2023-03-26 16:28 UTC, merged