Pre-emptively fetch answer reaction state
Retrospring/retrospring pull request #1459
Opened 2023-11-07 21:44 UTC by raccube

2023-11-12 00:24 UTC, pixeldesu requested changes
We talked about this in private already, I'll leave the feedback here just so we don't forget about it.

I'm not a fan of this approach because comparing against a pre-fetched set of IDs makes it harder to make independent components out of specific features. It brings a performance improvement, but at the cost of maintainability.

I'm personally not sure how to solve this. If a different way of caching, or using something like

> if a global containing a pre-cached set of IDs is available, prefer that over fetching data yourself

could allow for both cases.

2023-11-19 08:06 UTC, nilsding approved these changes

2023-11-26 18:34 UTC, raccube commented
@pixeldesu @nilsding I rewrote this using subqueries, so the additional lookup queries aren't required at all.

2023-11-27 21:07 UTC, pixeldesu approved these changes

2023-12-08 21:59 UTC, merged