Add links for jumping to rails admin on answers, questions and profiles
Retrospring/retrospring pull request #182
Opened 2021-08-05 18:40 UTC by raccube

2021-08-05 18:49 UTC, nilsding commented on app/views/answerbox/_actions.haml
> +        %a.dropdown-item{ href: rails_admin_path + "/answer/#{a.id}", target: '_blank' }
just `"#{rails_admin_path}/answer/#{a.id}"` would be fine too

2021-08-06 09:59 UTC, pixeldesu requested changes

2021-08-06 09:59 UTC, pixeldesu commented on app/views/user/_actions.haml
> +          %a.dropdown-item{ href: "#{rails_admin_path}/user/#{user.id}", target: '_blank' }
While those look fine now, couldn't we make it a bit cleaner?

Like, having a helper generate the full URL, being in parts the `rails_admin_path` but figuring the rest out itself? Working out the other URL fragment is the `resource` in some format + it's id

So having something like `rails_admin_path_for_resource(user)` would be swell, so we don't have a bunch of concatenation in the templates themselves!

2021-08-06 12:36 UTC, pixeldesu approved these changes
LGTM, but maybe fix the code coverage

2021-08-07 17:52 UTC, merged