Add share buttons to answers using Web Share API
Retrospring/retrospring pull request #183
Opened 2021-08-05 23:11 UTC by raccube

Example:
![IMG_2744](https://user-images.githubusercontent.com/6197148/128432806-76b4af57-b696-459b-8a5e-60f6f67eb525.jpg)

2021-08-08 12:49 UTC, pixeldesu requested changes

2021-08-08 12:49 UTC, pixeldesu commented on app/assets/stylesheets/components/_answerbox.scss
> +  }
mobile first, no downwards queries please. Use `media-breakpoint-up` instead. And inverse styling (having styles on mobile, reset on other queries if necessary)

2021-08-08 12:49 UTC, pixeldesu commented on app/javascript/retrospring/initializers/share.ts
> +}
* Initializers are meant to set up larger global features (Bootstrap, jQuery, etc. pp.), this is a single feature.
* The code doesn't need to be initialized if no `button[name=ab-share]` is present (save code execution)
* **Don't use jQuery!** It's planned to be removed (and it already is in a branch)

You can use the [`feature/webpacker` branch](https://github.com/Retrospring/retrospring/tree/feature/webpacker/app/javascript) as a reference on how I implemented features before!

2021-08-10 13:40 UTC, pixeldesu requested changes

2021-08-10 13:40 UTC, pixeldesu commented on app/javascript/packs/application.ts
> +document.addEventListener('turbolinks:load', initAnswerbox);
Eh?

2021-08-10 13:40 UTC, pixeldesu commented on app/javascript/retrospring/features/answerbox/index.ts
> +  }
Good, but this also breaks setting any `answerbox` related functionality if `navigator.share` is not there, maybe move this check to `createShareEvent`.

2021-08-10 13:40 UTC, pixeldesu commented on app/javascript/retrospring/features/answerbox/share.ts
> +    })
Hmm, this looks kinda ugly, we could just do an empty function as a base `noop` instead.

Maybe create one in `retrospring/utilities`

```suggestion
    })
    .then(noop)
    .catch(noop)
```

2021-08-10 13:41 UTC, raccube commented on app/javascript/packs/application.ts
> +document.addEventListener('turbolinks:load', initAnswerbox);
not sure how I managed that one

2021-08-10 14:08 UTC, pixeldesu commented on app/javascript/retrospring/utilities/noop.ts
> +export default () => void {
```suggestion
export default (): void => {
```

2021-08-10 14:09 UTC, pixeldesu commented on app/javascript/retrospring/utilities/noop.ts
> +export default () => void {
I'm actually suprised that's not a syntax error

2021-08-10 16:23 UTC, pixeldesu approved these changes

2021-08-10 18:26 UTC, merged