Add Link Proxy
Retrospring/retrospring pull request #249
Opened 2021-12-30 17:20 UTC by pixeldesu

Fixes #110 

Adds formatting to questions, but the only thing that is allowed are links. And if links are not the original host (or a whitelisted one) a link proxy will be shown instead, warning users of potential risk ahead.

To test this locally, don't forget to set the list of allowed hosts in `justask.yml`

2021-12-30 21:09 UTC, raccube approved these changes

2021-12-31 18:04 UTC, nilsding requested changes

2021-12-31 18:04 UTC, nilsding commented on spec/helpers/markdown_helper_spec.rb
> +  end
what's `#question_markdown`'s result on e.g...?

```markdown
**your account has been disabled**, [click here to enable it again](https://evil.example.com)
```

2021-12-31 18:04 UTC, nilsding commented on app/services/shared_markers.rb
> +    "<a href=\"#{linkfilter_path(url: link)}\" target=\"_blank\">#{link}</a>"
why not use `content_tag` here?

e.g. something like

```ruby
href = if ALLOWED_HOSTS.include?(URI(link).host)
         link
       else
         linkfilter_path(url: link)
       end

content_tag(:a, link, href: href, target: "_blank") # `link` will also be properly HTML escaped
```

I think these links should also be ignored by search engines, so the final content_tag would be e.g.

```ruby
content_tag(:a, link, href: href, target: "_blank", rel: "nofollow")
```

2021-12-31 18:04 UTC, nilsding commented on config/initializers/redcarpet.rb
> +ALLOWED_HOSTS = [
the name of this const is too generic.  Perhaps something like `ALLOWED_HOSTS_IN_MARKDOWN` is better here

2021-12-31 18:04 UTC, nilsding commented on app/views/static/linkfilter.haml
> +      %a.btn.btn-primary{ href: @link } I understand the risk, proceed!
add a `rel: "nofollow"` here so search engines don't count anything passed to the linkfilter

2021-12-31 20:48 UTC, raccube commented on app/services/shared_markers.rb
> +    "<a href=\"#{linkfilter_path(url: link)}\" target=\"_blank\">#{link}</a>"
+1 for the `rel=nofollow`

2021-12-31 20:53 UTC, pixeldesu commented on spec/helpers/markdown_helper_spec.rb
> +  end
literally no markup, that's the result
![](https://a.uguu.se/j2dv6r0mpccJ_firefox_BD2UOV5QEH.png)

only link and paragraph get processed so there's actual output

2021-12-31 21:26 UTC, nilsding approved these changes

2021-12-31 21:40 UTC, merged