Add translation for mute rules
Retrospring/retrospring pull request #356
Opened 2022-02-16 23:59 UTC by pixeldesu

New translations!

**Testing:**
* Visit `/settings/muted` and verify that the locales look fine and general functionality still works

2022-02-17 22:21 UTC, raccube approved these changes
Looks good, one small thing though.

2022-02-17 22:21 UTC, raccube commented on config/locales/voc.en.yml
> +    noauth: "requires authentication"
```suggestion
    noauth: "You must be signed in to do this."
```

2022-02-17 22:49 UTC, nilsding requested changes

2022-02-17 22:49 UTC, nilsding commented on config/locales/voc.en.yml
> +    noauth: "You must be signed in to do this."
Unexpected item in bagging area

2022-02-18 10:13 UTC, nilsding approved these changes

2022-02-18 11:50 UTC, merged