Allow users to change the display name of their anonymous askers
Retrospring/retrospring pull request #404
Opened 2022-06-21 12:53 UTC by raccube

2022-06-21 19:15 UTC, nilsding requested changes
looks good

2022-06-21 19:15 UTC, nilsding commented on db/schema.rb
> +
again?

2022-06-21 19:16 UTC, raccube commented on db/schema.rb
> +
Oops. I should reset my database.

2022-06-21 19:18 UTC, nilsding approved these changes

2022-06-23 14:48 UTC, nilsding approved these changes

2022-06-23 19:07 UTC, pixeldesu approved these changes

2022-06-23 19:29 UTC, merged