Add toggle for moderation view
Retrospring/retrospring pull request #409
Opened 2022-06-23 21:36 UTC by raccube

2022-06-25 11:38 UTC, pixeldesu requested changes

2022-06-25 11:38 UTC, pixeldesu commented on app/helpers/user_helper.rb
> +    "<abbr title='#{anonymous_identifier}'>#{anonymous_name(context_user)}</abbr>"
Please don't return raw HTML, always use `content_tag`

2022-06-26 18:23 UTC, raccube commented on app/helpers/user_helper.rb
> +    "<abbr title='#{anonymous_identifier}'>#{anonymous_name(context_user)}</abbr>"
863e49a

2022-06-26 18:46 UTC, pixeldesu approved these changes

2022-06-26 19:07 UTC, merged