Add interface to manage blocks
Retrospring/retrospring pull request #410
Opened 2022-06-23 23:15 UTC by pixeldesu

Adds a `/settings/blocks` page to manage (anonymous) blocks, listing all blocked users and allowing to unblock them from there.

**Testing:**
* Check the new views if they look fine
* Check if the translations are applied fine
* Check if (un)blocking on user profiles and the block settings page still works

2022-06-24 15:10 UTC, raccube requested changes
Some of the text reads a bit weird otherwise all good.

2022-06-24 15:10 UTC, raccube commented on config/locales/views.en.yml
> +          body: "Here every user you are currently blocking is listed with a quick option to unblock them. You can block users on their profile using the 'Actions' dropdown."
```suggestion
          body: "Here every user you are currently blocking is listed with a quick option to unblock them. You can block users on their profile from the 'Actions' dropdown."
```

2022-06-24 15:10 UTC, raccube commented on config/locales/views.en.yml
> +          body: "Here every anonymous user you are blocking is listed with a quick option to unblock them. Anonymous users can be blocked from questions in your inbox. To provide more context on who
```suggestion
          body: "Here every anonymous user you are blocking is listed with a quick option to unblock them. Anonymous users can be blocked from questions in your inbox. To provide more context on who you blocked, the question they asked you is shown."
```

2022-06-24 15:10 UTC, raccube commented on app/views/settings/_blocks.haml
> +      - @blocks.each do |block|
Do we maybe want to put in a "You are not blocking everyone." if this is empty?

2022-06-25 07:12 UTC, nilsding requested changes
looks good out, have some more suggestions on the wording though :-)

2022-06-25 07:12 UTC, nilsding commented on config/locales/views.en.yml
> +      none: "No one has been blocked yet"
this reads a bit too sterile, what about:

```suggestion
      none: "You are not blocking anyone."
```

2022-06-25 07:12 UTC, nilsding commented on config/locales/views.en.yml
> +          body: "Here every user you are currently blocking is listed with a quick option to unblock them. You can block users on their profile from the 'Actions' dropdown."
```suggestion
          body: "Each user you've blocked is listed here, along with a way to unblock them.  To block someone, use the 'Actions' dropdown on their profile page."
```

2022-06-25 07:12 UTC, nilsding commented on config/locales/views.en.yml
> +          body: "Here every anonymous user you are blocking is listed with a quick option to unblock them. Anonymous users can be blocked from questions in your inbox. To provide more context on who
one more :-) 

```suggestion
          body: "Each anonymous user you've blocked is listed here, along with a way to unblock them. We also display the question they asked you to add some more context. You can block anonymous users directly from the question in your inbox."
```

2022-06-25 10:06 UTC, nilsding approved these changes

2022-06-25 10:14 UTC, raccube approved these changes

2022-06-25 13:39 UTC, merged