Deduplicate shared logic in `TimelineController`
Retrospring/retrospring pull request #540
Opened 2022-07-19 15:28 UTC by raccube

2022-07-19 15:31 UTC, pixeldesu requested changes

2022-07-19 15:31 UTC, pixeldesu commented on app/controllers/timeline_controller.rb
> +    @title = generate_title("Public Timeline")
Missing locale!

2022-07-19 16:40 UTC, raccube commented on app/controllers/timeline_controller.rb
> +    @title = generate_title("Public Timeline")
Good catch

2022-07-19 18:47 UTC, pixeldesu approved these changes

2022-07-19 20:50 UTC, pixeldesu approved these changes

2022-07-21 13:50 UTC, nilsding commented on app/views/timeline/timeline.haml
> +- provide(:title, @title ||= APP_CONFIG["site_name"])
what's that `@title ||=` for?

2022-07-21 13:58 UTC, nilsding approved these changes
Lemons Greet The Monarch

2022-07-21 14:08 UTC, merged