List direct questions for current users or mods
Retrospring/retrospring pull request #630
Opened 2022-08-17 21:22 UTC by pixeldesu

Instead of completely removing direct questions from user pages, this now allows moderators (in unmask mode) and users that own the current page to view their direct questions.

2022-08-18 06:25 UTC, nilsding requested changes

2022-08-18 06:25 UTC, nilsding commented on app/helpers/user_helper.rb
> +  def belongs_to_current_user?
This method would be better suited as a private method inside UserController; helpers should be for views only.

btw, you can also use Ruby3's endless method definition syntax:
```ruby
private

def belongs_to_current_user? = @user == current_user
```

2022-08-20 13:08 UTC, nilsding approved these changes

2022-08-20 13:09 UTC, pixeldesu commented
So I adjusted this, but I didn't manage to properly get tests done for `UserController#questions`. Here's my attempt in a gist: https://gist.github.com/pixeldesu/f80868e0c196227c0adb3e6780ae31b9

The first test was similar to the others but that didn't work either and checking for the size of the instance variable doesn't yield the right answer too, even though it works fine as expected in the frontend. (the checks for no renders/null length pass because the first one fails, etc. etc.)

2022-08-20 13:11 UTC, nilsding commented
it's because you used `let` instead of `let!`; `let!` expressions are evaluated eagerly whereas `let` ones will get evaluated the first time they're called

2022-08-20 13:15 UTC, pixeldesu commented
It wasn't working with a question being created in a `before` block either. And I just tried it, `@question.size` still is 0 with `let!`.

2022-08-20 14:16 UTC, nilsding commented
Ah, found it.  The question is created as an anonymous one.  Pass `author_is_anonymous: false` to the `FactoryBot.create` call and then it does what it should.

2022-08-20 14:19 UTC, pixeldesu commented
Yup, that fixed that.

I will adjust the other tests (the moderation one wasn't properly implemented yet) and then push those. Wanted to have this behaviour tested properly because it could lead to unwanted infos being leaked.

2022-08-20 15:13 UTC, nilsding approved these changes

2022-08-20 15:13 UTC, nilsding commented on spec/controllers/user_controller_spec.rb
> +    context "current user signed in" do
```suggestion
    context "when the current user is the question author" do
```

2022-08-20 15:13 UTC, nilsding commented on spec/controllers/user_controller_spec.rb
>      context "user signed in" do
```suggestion
    context "when the current user is someone else" do
```

2022-08-20 15:13 UTC, nilsding commented on spec/controllers/user_controller_spec.rb
> +    context "moderator unmasked" do
```suggestion
    context "when a moderator uses unmask" do
```

2022-08-20 15:13 UTC, nilsding commented on spec/controllers/user_controller_spec.rb
> +    context "user not signed in" do
```suggestion
    context "when user is not signed in" do
```

2022-08-20 15:21 UTC, nilsding approved these changes

2022-08-20 15:21 UTC, merged