Add a Stimulus-based character count for questions and comments
Retrospring/retrospring pull request #736
Opened 2022-10-13 20:58 UTC by pixeldesu

_First Stimulus controller!_

Finally adds a character count to questions and disables the button/action if the maximum is reached.

**Testing:**
* Test sending comments and questions
* Test going over the max character count for both types and verify the actions being disabled

2022-10-24 21:11 UTC, raccube approved these changes

2022-10-24 21:27 UTC, nilsding requested changes
hm, the char count doesn't reset after asking a question (both in the user page and the ask followers modal).  comments works fine!

2022-10-31 20:29 UTC, pixeldesu commented
@nilsding I fixed the questionbox character counts resetting. Not necessary in a way that is clean (I'd like it all to be Stimulus controller-based), but this works for now.

2022-10-31 21:52 UTC, nilsding approved these changes

2022-11-03 16:47 UTC, raccube approved these changes
Doesn't reset when submitted but update correctly after posting now.

2022-11-03 18:22 UTC, merged