Replace inbox sidebar with action bar
Retrospring/retrospring pull request #738
Opened 2022-10-16 14:43 UTC by pixeldesu

The sidebar layout isn't particularly great, especially because it doesn't contain that much info or actions for the size it takes.

The action bar at the top uses way less space, and is in front of the inbox content on mobile, compared to at the bottom with the sidebar. A lot of people might have missed some inbox functionality through this.

|         | Before | After |
|---------|--------|-------|
| Mobile  | ![image](https://user-images.githubusercontent.com/1774242/196041629-8c61b91e-7ea9-4d1a-be00-a89c34e61132.png) | ![image](https://user-images.githubusercontent.com/1774242/196041679-e370b959-cf1c-4a76-a2cc-fdc88edd1fcd.png) |
| Desktop | ![image](https://user-images.githubusercontent.com/1774242/196041751-2b2ad703-2925-47fd-93dc-fb00b7a0c7e6.png) | ![image](https://user-images.githubusercontent.com/1774242/196041765-9faee627-3680-403f-9784-3ab4d0b67eda.png) |

2022-10-20 08:36 UTC, raccube requested changes
I like this but I don't think it's very clear.

Here's a few things I think would make it better:
- Change the placeholder text on the user filter to "Filter by user…"
- Change the "Get new question" button text to "Generate question".

2022-10-21 22:51 UTC, nilsding commented on app/views/inbox/_actions.haml
> +        %button.btn.btn-danger.ml-1{ type: :button, id: delete_id, disabled: (disabled ? :disabled : nil), data: { ib_count: inbox_count } }
```suggestion
        %button.btn.btn-danger.ml-1{ type: :button, title: t(".actions.delete"), id: delete_id, disabled: (disabled ? :disabled : nil), data: { ib_count: inbox_count } }
```

2022-10-21 22:51 UTC, nilsding commented on app/views/inbox/_actions.haml
> +          %button.btn.btn-default{ data: { toggle: :dropdown }, aria: { expanded: false } }
```suggestion
          %button.btn.btn-default{ title: t(".share.heading"), data: { toggle: :dropdown }, aria: { expanded: false } }
```

so it has a hover tooltip

2022-10-21 23:02 UTC, nilsding commented
I like the general idea of this, but I feel like it's taking up a bit too much space.  Adding `padding: .5rem 1.25rem;` to the `.card-body` styling of the toolbar makes it a bit more comfy I think:
 
<img width="954" alt="Screenshot 2022-10-22 at 01 00 10" src="https://user-images.githubusercontent.com/1809170/197303102-f747114e-fbcc-4326-8b45-02adf9b59ba5.png">

2022-10-24 10:42 UTC, raccube approved these changes
With the exception of @nilsding's comment, I think it looks good.

2022-10-24 10:55 UTC, pixeldesu commented
@nilsding I have made a compromise, I decreased the vertical spacing, but not as much as you suggested.

![image](https://user-images.githubusercontent.com/1774242/197510525-2b3b0bf5-3803-4948-b544-4d03034c2d30.png)

This adjustment is `padding: .75rem 1.25rem;` so the spacing matches Bootstraps `card-header` which we also use in answerboxes and inbox entries.

2022-10-24 11:39 UTC, nilsding commented
Jo passt.

side note: I don't like how the share button looks more like just an icon than a button, but this is a general bootstrap thingy and out of scope for this PR

2022-10-24 11:40 UTC, nilsding approved these changes

2022-10-24 11:41 UTC, pixeldesu commented
Hmm, I just didn't want to give it any actionable button color that gives it some sort of urgency

I could reorder it to share, generate, delete so it doesn't look that much out of place.

2022-10-24 11:48 UTC, nilsding commented
all I'm missing is some borders :D  but for me the order is good as it is now

2022-10-24 11:58 UTC, merged