Adjust some text across the repository
Retrospring/retrospring pull request #777
Opened 2022-11-01 00:30 UTC by pixeldesu

* Removed all-contributors from README (and its config file)
* Added a full license claim to the README
* Included a description of Retrospring to the top of the README, instead of the mention of it being a detached fork
* Adjusted wording of the CONTRIBUTING.md and removed some outdated info

2022-11-01 01:01 UTC, nilsding requested changes

2022-11-01 01:01 UTC, nilsding commented on README.md
> +Retrospring is a **free, open-source social network** following the Q/A (question and answer) principle of sites like Formspring, ask.fm or CuriousCat. Users can create accounts on Retrospring to rec
it's late, so the text won't make sense (probably), but maybe:

```suggestion
Retrospring is a **free, open-source social network** following the Q/A (question and answer) principle of sites like
Formspring, ask.fm or CuriousCat.  Users can create accounts on Retrospring to receive questions from other users of the site
and/or anonymous people on the Internet.  They can also follow each other on Retrospring to see new answers of their friends in
the timeline and to ask their followers interesting questions.
```

(also 120 character word wrap for easier reviewing :v)

2022-11-01 01:01 UTC, nilsding commented on README.md
>  ## License
```suggestion
## Licence
```

2022-11-01 11:18 UTC, raccube requested changes

2022-11-01 11:18 UTC, raccube commented on .github/CONTRIBUTING.md
> +* Please use the core team standard of `feature/*` branch naming.
```suggestion
* Please use the core team standard of `feature/*` or `fix/*` branch naming.
```

2022-11-01 11:18 UTC, raccube commented on .github/CONTRIBUTING.md
>    commits. You can do this using the interactive rebase command.
```suggestion
  commits. You can do this using the [interactive rebase](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_changing_multiple) command.
```

2022-11-01 12:05 UTC, pixeldesu commented on README.md
>  ## License
I do get this is the traditional English way of writing that, but my _one fear_ about this is us getting a bunch of "Fix typo in README" PRs once this repository gains traction, because everyone else is using License as well. 🤔

2022-11-03 09:45 UTC, nilsding approved these changes

2022-11-03 16:41 UTC, raccube approved these changes

2022-11-03 18:00 UTC, merged