Migrate mute rule handling to Turbo Streams
Retrospring/retrospring pull request #811
Opened 2022-11-18 21:57 UTC by pixeldesu

Same as #809 but for the entire mute rule functionality set. Removed the update action because we don't update `MuteRule`s ever.

Also sets up Pundit (closes #80) to handle authorization for the `destroy` action, instead of an inlined check as in the AJAX action before.

**Testing:**
* Test creating/deleting mute rules

2022-11-20 13:55 UTC, raccube approved these changes

2022-11-20 14:07 UTC, raccube requested changes
Ignore the previous approve, that was an accident.

The field doesn't empty after submitting.

2022-11-20 15:45 UTC, pixeldesu commented
Fixed, the form is now also replaced on submit and I added a Stimulus controller to autofocus the input once that happens. (no, the `autofocus` attribute did not work for me)

2022-11-21 19:03 UTC, raccube approved these changes

2022-11-21 19:26 UTC, merged