Rework exporter
Retrospring/retrospring pull request #844
Opened 2022-12-10 03:39 UTC by nilsding

this PR reworks the data exporter that I wrote a few days before the initial shutdown of retrospring.  It was long overdue for a rework as evidenced by the recent breakages.

The new exporter is easily testable, only exports files as JSON, doesn't shell out to the system's `tar` and should therefore be truly cross-platform.  
It also uses all available fields from each model, so changing the database schema will update the exported data too.  This also requires the exporter specs to be adapted to e.g. ensure sensitive fields don't end up in the export.

Oh, and the "Your data is ready" question is gone too.  There's now a nice notification for it:

<table><tbody><tr><td>
<img width="585" alt="Screenshot 2022-12-10 at 04 17 52" src="https://user-images.githubusercontent.com/1809170/206827193-1c1daa33-92f9-4898-99a5-d6a8736f5ed8.png"></td><td>
<img width="1164" alt="Screenshot 2022-12-10 at 04 18 07" src="https://user-images.githubusercontent.com/1809170/206827199-dfffc840-5ee7-4a09-9747-b9d4c7277068.png"></td></tr></tbody></table>

I tested this locally with my S3 at home (radosgw rules!), seems to work fine.  Didn't really test local uploads as I'm affected by #822 here.

Here's what the resulting zip file looks for a user who has profile pictures:
```
% 7z l export-107825323001175502-xhps5tgt6czmb7pj9f0cb5ce31gjh056.zip 

7-Zip [64] 17.04 : Copyright (c) 1999-2021 Igor Pavlov : 2017-08-28
p7zip Version 17.04 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,8 CPUs LE)

Scanning the drive for archives:
1 file, 3759125 bytes (3672 KiB)

Listing archive: /Users/foxy/Downloads/export-107825323001175502-xhps5tgt6czmb7pj9f0cb5ce31gjh056.zip

--
Path = /Users/foxy/Downloads/export-107825323001175502-xhps5tgt6czmb7pj9f0cb5ce31gjh056.zip
Type = zip
Physical Size = 3759125
Comment = justask export done for Jyrki on 2022-12-09T23:40:34Z

   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
2022-12-10 00:40:34 D....            0            0  export-107825323001175502-xhps5tgt6czmb7pj9f0cb5ce31gjh056
2022-12-10 00:40:34 D....            0            0  export-107825323001175502-xhps5tgt6czmb7pj9f0cb5ce31gjh056/pictures
2022-12-10 00:40:34 .....        25242          853  export-107825323001175502-xhps5tgt6czmb7pj9f0cb5ce31gjh056/answers.json
2022-12-10 00:40:34 .....          974          338  export-107825323001175502-xhps5tgt6czmb7pj9f0cb5ce31gjh056/comments.json
2022-12-10 00:40:34 .....          906          246  export-107825323001175502-xhps5tgt6czmb7pj9f0cb5ce31gjh056/appendables.json
2022-12-10 00:40:34 .....          452          179  export-107825323001175502-xhps5tgt6czmb7pj9f0cb5ce31gjh056/mute_rules.json
2022-12-10 00:40:34 .....        20236         2308  export-107825323001175502-xhps5tgt6czmb7pj9f0cb5ce31gjh056/inbox_entries.json
2022-12-10 00:40:34 .....          788          326  export-107825323001175502-xhps5tgt6czmb7pj9f0cb5ce31gjh056/theme.json
2022-12-10 00:40:34 .....          268          158  export-107825323001175502-xhps5tgt6czmb7pj9f0cb5ce31gjh056/relationships.json
2022-12-10 00:40:34 .....        27290         2981  export-107825323001175502-xhps5tgt6czmb7pj9f0cb5ce31gjh056/questions.json
2022-12-10 00:40:34 .....         2125          798  export-107825323001175502-xhps5tgt6czmb7pj9f0cb5ce31gjh056/user.json
2022-12-10 00:40:34 .....      1904283      1904850  export-107825323001175502-xhps5tgt6czmb7pj9f0cb5ce31gjh056/pictures/profile_picture_original_bild1.png
2022-12-10 00:40:34 .....       462268       462397  export-107825323001175502-xhps5tgt6czmb7pj9f0cb5ce31gjh056/pictures/profile_picture_large_bild1.png
2022-12-10 00:40:34 .....       120993       121012  export-107825323001175502-xhps5tgt6czmb7pj9f0cb5ce31gjh056/pictures/profile_picture_medium_bild1.png
2022-12-10 00:40:34 .....        13711        13675  export-107825323001175502-xhps5tgt6czmb7pj9f0cb5ce31gjh056/pictures/profile_picture_small_bild1.png
2022-12-10 00:40:34 .....       369385       369231  export-107825323001175502-xhps5tgt6czmb7pj9f0cb5ce31gjh056/pictures/profile_header_original_mastodon_header.png
2022-12-10 00:40:34 .....       548834       548729  export-107825323001175502-xhps5tgt6czmb7pj9f0cb5ce31gjh056/pictures/profile_header_web_mastodon_header.png
2022-12-10 00:40:34 .....        79717        79475  export-107825323001175502-xhps5tgt6czmb7pj9f0cb5ce31gjh056/pictures/profile_header_mobile_mastodon_header.png
2022-12-10 00:40:34 .....       246525       246325  export-107825323001175502-xhps5tgt6czmb7pj9f0cb5ce31gjh056/pictures/profile_header_retina_mastodon_header.png
------------------- ----- ------------ ------------  ------------------------
2022-12-10 00:40:34            3823997      3753881  17 files, 2 folders
```

and here's one for one who doesn't:
```
% 7z l export-109397513672924100-e1dnxyd567yj5gspo6h6x1oexstui9rc.zip 

7-Zip [64] 17.04 : Copyright (c) 1999-2021 Igor Pavlov : 2017-08-28
p7zip Version 17.04 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,8 CPUs LE)

Scanning the drive for archives:
1 file, 3544 bytes (4 KiB)      

Listing archive: /Users/foxy/Downloads/export-109397513672924100-e1dnxyd567yj5gspo6h6x1oexstui9rc.zip

--
Path = /Users/foxy/Downloads/export-109397513672924100-e1dnxyd567yj5gspo6h6x1oexstui9rc.zip
Type = zip
Physical Size = 3544
Comment = justask export done for Cringe on 2022-12-10T03:19:26Z

   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
2022-12-10 04:19:26 D....            0            0  export-109397513672924100-e1dnxyd567yj5gspo6h6x1oexstui9rc
2022-12-10 04:19:26 D....            0            0  export-109397513672924100-e1dnxyd567yj5gspo6h6x1oexstui9rc/pictures
2022-12-10 04:19:26 .....          327          191  export-109397513672924100-e1dnxyd567yj5gspo6h6x1oexstui9rc/questions.json
2022-12-10 04:19:26 .....           23           25  export-109397513672924100-e1dnxyd567yj5gspo6h6x1oexstui9rc/mute_rules.json
2022-12-10 04:19:26 .....           26           28  export-109397513672924100-e1dnxyd567yj5gspo6h6x1oexstui9rc/inbox_entries.json
2022-12-10 04:19:26 .....           21           23  export-109397513672924100-e1dnxyd567yj5gspo6h6x1oexstui9rc/comments.json
2022-12-10 04:19:26 .....           24           26  export-109397513672924100-e1dnxyd567yj5gspo6h6x1oexstui9rc/appendables.json
2022-12-10 04:19:26 .....          315          167  export-109397513672924100-e1dnxyd567yj5gspo6h6x1oexstui9rc/answers.json
2022-12-10 04:19:26 .....         1968          623  export-109397513672924100-e1dnxyd567yj5gspo6h6x1oexstui9rc/user.json
2022-12-10 04:19:26 .....          508          196  export-109397513672924100-e1dnxyd567yj5gspo6h6x1oexstui9rc/relationships.json
------------------- ----- ------------ ------------  ------------------------
2022-12-10 04:19:26               3212         1279  8 files, 2 folders
```

resolves #78, resolves #834

2022-12-10 11:20 UTC, pixeldesu requested changes
I tested the exporter locally (and aside the broken paths to the upload) it works fine.

Some things:
* Please clear the notification if the export settings are viewed.
* `inbox_entries` feels kind of useless without any text. Just the IDs is not a useful export. So either we include the question text as well, or just drop that part of the export.

2022-12-10 15:01 UTC, pixeldesu approved these changes

2022-12-11 18:54 UTC, raccube approved these changes
Not sure how I feel about the naming of `appendables.json` but otherwise looks good to me.

2022-12-11 18:56 UTC, nilsding commented
I just named the files after the model names.  it can always be renamed later if needed

2022-12-11 18:56 UTC, merged