Revoke Twitter connection when the token is revoked
Retrospring/retrospring pull request #891
Opened 2023-01-01 22:46 UTC by raccube

2023-01-01 22:58 UTC, pixeldesu approved these changes

2023-01-02 07:06 UTC, nilsding requested changes

2023-01-02 07:06 UTC, nilsding commented on app/workers/share_worker.rb
> +    user_service = find_service(user_id, service)
could use an instance variable here

```suggestion
    @user_service = User.find(user_id).services.find_by(type: "Services::#{service.camelize}")
```

2023-01-02 07:06 UTC, nilsding commented on app/workers/share_worker.rb
> +    user_service.destroy
...which can then be used here to destroy the service

```suggestion
    @user_service.destroy
```

-> 1 query less!

2023-01-02 07:06 UTC, nilsding commented on app/workers/share_worker.rb
> +  def find_service(user_id, service) = User.find(user_id).services.find_by(type: "Services::#{service.camelize}")
(and then get rid of that method)

```suggestion
```

2023-01-02 07:06 UTC, nilsding commented on app/workers/share_worker.rb
>      user_service.post(Answer.find(answer_id))
```suggestion
    @user_service.post(Answer.find(answer_id))
```

2023-01-02 08:38 UTC, nilsding approved these changes

2023-01-02 09:08 UTC, merged