Upgrade to Bootstrap 5
Retrospring/retrospring pull request #919
Opened 2023-01-04 16:16 UTC by pixeldesu

_Way less effort than 3 -> 4 at least!_

You know the drill. Use the page in all possible ways and find potential problems and report them back.

Resolves #399

2023-01-04 20:17 UTC, nilsding requested changes
looks really good so far

noticed a few odd things though:
- monospacen't
- inputs in `/settings/muted` need some more spacing
- (not important): tabs in discover look a bit out of place with the active background

2023-01-04 20:32 UTC, raccube requested changes
Menus don't open on mobile.

2023-01-04 22:08 UTC, raccube approved these changes

2023-01-05 04:52 UTC, nilsding approved these changes

2023-01-05 09:35 UTC, merged